#!python3

import os
os.system("cls")

def counterGenerator() :
    countValue = 0
    def getCounter() :
        nonlocal countValue
        countValue += 1
        return countValue
    return getCounter

if __name__ == "__main__" :
    print("\nDisplaying the values generated by counter...", end="\n")
    closureCounter = counterGenerator()
    
    for loopIndex in range(10) :
        print("\nThe current counter value is: %d"%(closureCounter()), end="\n")

"""
Output:
-------
Displaying the values generated by counter...

The current counter value is: 1

The current counter value is: 2

The current counter value is: 3

The current counter value is: 4

The current counter value is: 5

The current counter value is: 6

The current counter value is: 7

The current counter value is: 8

The current counter value is: 9

The current counter value is: 10

"""